### ISSUE TITLE
ARM related

### ISSUE THREAD

**Issue by soma-c18** [t-crest/patmos-llvm#13]
When i try to compile patmos-clang for ARM i am getting no available target error...
~/t-crest$ patmos-clang -target arm-linux-gnueabi -marm -mserialize=/home/soma/if-testpat34.pml /home/soma/if-test34.c 
patmos-clang-3.4: warning: argument unused during compilation: '-mserialize=/home/soma/if-testpat34.pml'
error: unable to create target: 'No available targets are compatible with this
      triple, see -version for the available targets.'
1 error generated.

**Comment by schoeberl** [comment]
What is the purpose to compile the patmos-clang, which targets the Patmos processor, for an ARM target? Better do this from the upstream version of LLVM.

**Comment by soma-c18** [comment]
I want to generate a pml file which is required for wcet estimation using platin tool, I am trying to work on predicated architecture and trying to analyze  if-conversion optimization in Llvm.

**Comment by schoeberl** [comment]
Why then not just working with the Patmos version? Patmos is an open source processor ready for tinkering and changing to be used in research. Patmos is a fully predicated processor. I would be happy if you can contribute with some support of if-conversion to the Patmos LLVM compiler.

Martin

**Comment by soma-c18** [comment]
Thank you for the answer, can you suggest where or how  to start as in the t-crest there is llvm and already there is the if-conversion.cpp file, where in patmos the  modification has to be made.

**Comment by schoeberl** [comment]
I do not really understand your question. A general start to use Patmos and its compiler can be found at https://github.com/t-crest/patmos and in the Patmos handbook (http://patmos.compute.dtu.dk/patmos_handbook.pdf).

**Comment by schoeberl** [comment]
probably solved
