### ISSUE TITLE
Extract Platin into its own repository

### ISSUE THREAD

**Issue by Emoun** [t-crest/patmos-llvm#26]
Much like with [the patmos simulator](https://github.com/t-crest/patmos/issues/60), I would like to split of the `platin` tool into its own repository under t-crest.

`platin` doesn't depend on LLVM in any way (it's even written in ruby and not c++) and neither does LLVM directly depend of `platin`. Extracting it into its own repository will give us more flexibility and enable us to independently work on it without having to worry about LLVM. It will also allow for a proper CI setup for it.

**Comment by Emoun** [comment]
@schoeberl Do you have any objections to this? If not, could I get you to make a new repository where `platin` can live moving forward?

**Comment by schoeberl** [comment]
Done. Sorry for the delay.
