### ISSUE TITLE
Handling unresolved calls in PML

### ISSUE THREAD

**Issue by alexjordan** [t-crest/patmos-llvm#7]
Different parts of platin currently fail to process functions with unresolved calls (e.g. flowfact transformation, visualization). @dlp proposed trace analysis to identify some call targets, but this cannot handle calls in parts of the program not executed during the trace. (Platin testcase created here: https://github.com/t-crest/patmos-benchmarks/blob/master/tests/platin/22-call-any.c)

To manually resolve the calls (or ignore them), we could ultimately use
1. source code annotations 
2. external annotations

Both should update a programs PML file in some way. 5a6cc5e adds an experimental platin tool to modify program information in a PML file. Program elements are selected by matching an XPath-inspired _PMLPath_. The only modification action supported right now is --clear-callees (clears the callee list in selected instructions), removing or replacing modifications could be added as well.
### Proposed PMLPath (by example):

The first segment of the path selects the set of bitcode `bc` or machine code `mc` functions; the following segments represent _function_, _basic block_, _instruction_, respectively. Matching predicates are of the form `[@property=name]`, all elements are selected using `*`.

The bitcode and the machine code function 'main':
    `/*/[@label=main]`

  All blocks in bitcode function 'main':
    `/bc/[@label=main]/*`

  All instructions in bitcode function 'main' that call function 'foo':
    `/bc/[@label=main]/*/[@callees=foo]`

**Comment by Emoun** [comment]
Closing as this issue seems solved.
